name: Build env

inputs:
  python-version:
    required: false
    type: string
    default: "3.13"

runs:
  using: "composite"

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.2"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install project
      run: uv sync --locked --all-extras --dev
      shell: bash