name: Release and Upload Python Package on PyPI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Call CI
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Deploy
    needs: [ci]
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup the environment
        uses: ./.github/actions/build_env

      - name: Install auditwheel
        run: |
          python -m pip install auditwheel

      - name: Build package
        run: uv build

      - name: Upload dist files
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package
        run: |
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}

  release:
    name: Release version
    needs: [deploy]
    uses: ./.github/workflows/github_release.yml